// Extension file untuk menambahkan 40 produk dummy lagi
// Total akan menjadi 50 produk

final List<Map<String, dynamic>> additionalDummyProducts = [
  {
    'id': 'product_011',
    'sellerId': 'seller_002',
    'name': 'Ikan Asin Jambal Roti',
    'description': 'Ikan asin jambal roti kualitas premium. Sudah dibersihkan dan siap dimasak.',
    'price': 65000.0,
    'stock': 20,
    'category': 'Ikan & Seafood',
    'images': ['https://via.placeholder.com/300x300?text=Ikan+Asin'],
    'mainImageIndex': 0,
    'sku': 'IKN-ASN-011',
    'hasDiscount': true,
    'discountPrice': 58000.0,
    'discountStartDate': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
    'discountEndDate': DateTime.now().add(const Duration(days: 4)).toIso8601String(),
    'minOrder': 1,
    'maxOrder': 5,
    'weightInGrams': 500,
    'length': 25.0,
    'width': 15.0,
    'height': 3.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['ikan', 'asin', 'jambal', 'seafood'],
    'createdAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_012',
    'sellerId': 'seller_001',
    'name': 'Keripik Singkong Balado',
    'description': 'Keripik singkong dengan bumbu balado yang pedas dan gurih. Camilan favorit keluarga.',
    'price': 15000.0,
    'stock': 45,
    'category': 'Camilan',
    'images': ['https://via.placeholder.com/300x300?text=Keripik+Balado'],
    'mainImageIndex': 0,
    'sku': 'KRP-SGK-012',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 2,
    'maxOrder': 20,
    'weightInGrams': 150,
    'length': 18.0,
    'width': 12.0,
    'height': 4.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['keripik', 'singkong', 'balado', 'pedas'],
    'createdAt': DateTime.now().subtract(const Duration(hours: 6)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_013',
    'sellerId': 'seller_002',
    'name': 'Bumbu Gulai Instan',
    'description': 'Bumbu gulai instan dengan rasa autentik. Praktis dan mudah digunakan.',
    'price': 12000.0,
    'stock': 60,
    'category': 'Bumbu Masak',
    'images': ['https://via.placeholder.com/300x300?text=Bumbu+Gulai'],
    'mainImageIndex': 0,
    'sku': 'BMB-GUL-013',
    'hasDiscount': true,
    'discountPrice': 10000.0,
    'discountStartDate': DateTime.now().toIso8601String(),
    'discountEndDate': DateTime.now().add(const Duration(days: 7)).toIso8601String(),
    'minOrder': 3,
    'maxOrder': 25,
    'weightInGrams': 50,
    'length': 8.0,
    'width': 6.0,
    'height': 1.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['bumbu', 'gulai', 'instan', 'praktis'],
    'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_014',
    'sellerId': 'seller_001',
    'name': 'Susu Kambing Murni',
    'description': 'Susu kambing segar tanpa pengawet. Baik untuk kesehatan dan pencernaan.',
    'price': 25000.0,
    'stock': 15,
    'category': 'Minuman',
    'images': ['https://via.placeholder.com/300x300?text=Susu+Kambing'],
    'mainImageIndex': 0,
    'sku': 'SSU-KMB-014',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 1,
    'maxOrder': 10,
    'weightInGrams': 500,
    'length': 8.0,
    'width': 8.0,
    'height': 12.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['susu', 'kambing', 'murni', 'sehat'],
    'createdAt': DateTime.now().subtract(const Duration(hours: 4)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_015',
    'sellerId': 'seller_002',
    'name': 'Abon Sapi Premium',
    'description': 'Abon sapi premium dengan tekstur halus dan rasa gurih. Cocok untuk sarapan.',
    'price': 85000.0,
    'stock': 8,
    'category': 'Makanan Olahan',
    'images': ['https://via.placeholder.com/300x300?text=Abon+Sapi'],
    'mainImageIndex': 0,
    'sku': 'ABN-SPI-015',
    'hasDiscount': true,
    'discountPrice': 75000.0,
    'discountStartDate': DateTime.now().subtract(const Duration(hours: 12)).toIso8601String(),
    'discountEndDate': DateTime.now().add(const Duration(days: 2)).toIso8601String(),
    'minOrder': 1,
    'maxOrder': 3,
    'weightInGrams': 250,
    'length': 12.0,
    'width': 8.0,
    'height': 6.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['abon', 'sapi', 'premium', 'halus'],
    'createdAt': DateTime.now().subtract(const Duration(days: 3)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_016',
    'sellerId': 'seller_001',
    'name': 'Tahu Sutra Segar',
    'description': 'Tahu sutra dengan tekstur lembut dan halus. Dibuat dari kedelai pilihan.',
    'price': 6000.0,
    'stock': 50,
    'category': 'Protein Nabati',
    'images': ['https://via.placeholder.com/300x300?text=Tahu+Sutra'],
    'mainImageIndex': 0,
    'sku': 'THU-STR-016',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 5,
    'maxOrder': 30,
    'weightInGrams': 200,
    'length': 10.0,
    'width': 10.0,
    'height': 3.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['tahu', 'sutra', 'segar', 'lembut'],
    'createdAt': DateTime.now().subtract(const Duration(hours: 2)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_017',
    'sellerId': 'seller_002',
    'name': 'Dendeng Balado Padang',
    'description': 'Dendeng balado khas Padang dengan bumbu rempah yang kaya. Tahan lama dan lezat.',
    'price': 150000.0,
    'stock': 5,
    'category': 'Makanan Olahan',
    'images': ['https://via.placeholder.com/300x300?text=Dendeng+Balado'],
    'mainImageIndex': 0,
    'sku': 'DND-BLD-017',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 1,
    'maxOrder': 2,
    'weightInGrams': 300,
    'length': 15.0,
    'width': 10.0,
    'height': 2.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['dendeng', 'balado', 'padang', 'rempah'],
    'createdAt': DateTime.now().subtract(const Duration(days: 4)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_018',
    'sellerId': 'seller_001',
    'name': 'Keju Mozarella Lokal',
    'description': 'Keju mozarella buatan lokal dengan kualitas premium. Cocok untuk pizza dan pasta.',
    'price': 45000.0,
    'stock': 12,
    'category': 'Dairy',
    'images': ['https://via.placeholder.com/300x300?text=Keju+Mozarella'],
    'mainImageIndex': 0,
    'sku': 'KJU-MOZ-018',
    'hasDiscount': true,
    'discountPrice': 40000.0,
    'discountStartDate': DateTime.now().toIso8601String(),
    'discountEndDate': DateTime.now().add(const Duration(days: 3)).toIso8601String(),
    'minOrder': 1,
    'maxOrder': 5,
    'weightInGrams': 250,
    'length': 12.0,
    'width': 8.0,
    'height': 4.0,
    'status': 'active',
    'hasHalalCertification': false,
    'tags': ['keju', 'mozarella', 'lokal', 'premium'],
    'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_019',
    'sellerId': 'seller_002',
    'name': 'Sirup Markisa Asli',
    'description': 'Sirup markisa dari buah asli tanpa pewarna buatan. Segar dan menyehatkan.',
    'price': 28000.0,
    'stock': 25,
    'category': 'Minuman',
    'images': ['https://via.placeholder.com/300x300?text=Sirup+Markisa'],
    'mainImageIndex': 0,
    'sku': 'SRP-MRK-019',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 2,
    'maxOrder': 10,
    'weightInGrams': 600,
    'length': 8.0,
    'width': 8.0,
    'height': 18.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['sirup', 'markisa', 'asli', 'segar'],
    'createdAt': DateTime.now().subtract(const Duration(hours: 10)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_020',
    'sellerId': 'seller_001',
    'name': 'Roti Tawar Gandum',
    'description': 'Roti tawar gandum utuh yang sehat dan bergizi. Tanpa pengawet berbahaya.',
    'price': 18000.0,
    'stock': 0,
    'category': 'Roti & Kue',
    'images': ['https://via.placeholder.com/300x300?text=Roti+Gandum'],
    'mainImageIndex': 0,
    'sku': 'RTI-GND-020',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 1,
    'maxOrder': 5,
    'weightInGrams': 400,
    'length': 20.0,
    'width': 12.0,
    'height': 8.0,
    'status': 'inactive',
    'hasHalalCertification': true,
    'tags': ['roti', 'gandum', 'sehat', 'bergizi'],
    'createdAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_021',
    'sellerId': 'seller_002',
    'name': 'Petis Udang Sidoarjo',
    'description': 'Petis udang khas Sidoarjo dengan rasa gurih dan aroma yang khas.',
    'price': 22000.0,
    'stock': 18,
    'category': 'Bumbu Masak',
    'images': ['https://via.placeholder.com/300x300?text=Petis+Udang'],
    'mainImageIndex': 0,
    'sku': 'PTS-UDG-021',
    'hasDiscount': true,
    'discountPrice': 19000.0,
    'discountStartDate': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
    'discountEndDate': DateTime.now().add(const Duration(days: 5)).toIso8601String(),
    'minOrder': 1,
    'maxOrder': 8,
    'weightInGrams': 200,
    'length': 8.0,
    'width': 8.0,
    'height': 6.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['petis', 'udang', 'sidoarjo', 'gurih'],
    'createdAt': DateTime.now().subtract(const Duration(days: 3)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_022',
    'sellerId': 'seller_001',
    'name': 'Yogurt Probiotik Alami',
    'description': 'Yogurt dengan probiotik alami yang baik untuk pencernaan. Tanpa gula tambahan.',
    'price': 15000.0,
    'stock': 30,
    'category': 'Dairy',
    'images': ['https://via.placeholder.com/300x300?text=Yogurt+Probiotik'],
    'mainImageIndex': 0,
    'sku': 'YGT-PRB-022',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 2,
    'maxOrder': 15,
    'weightInGrams': 200,
    'length': 8.0,
    'width': 8.0,
    'height': 10.0,
    'status': 'active',
    'hasHalalCertification': false,
    'tags': ['yogurt', 'probiotik', 'alami', 'sehat'],
    'createdAt': DateTime.now().subtract(const Duration(hours: 6)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_023',
    'sellerId': 'seller_002',
    'name': 'Teri Medan Krispi',
    'description': 'Teri medan yang sudah digoreng krispi. Siap santap dan tahan lama.',
    'price': 35000.0,
    'stock': 22,
    'category': 'Ikan & Seafood',
    'images': ['https://via.placeholder.com/300x300?text=Teri+Krispi'],
    'mainImageIndex': 0,
    'sku': 'TRI-MDN-023',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 1,
    'maxOrder': 10,
    'weightInGrams': 150,
    'length': 15.0,
    'width': 10.0,
    'height': 3.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['teri', 'medan', 'krispi', 'siap santap'],
    'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_024',
    'sellerId': 'seller_001',
    'name': 'Selai Strawberry Homemade',
    'description': 'Selai strawberry buatan rumah dengan buah asli. Manis alami tanpa pengawet.',
    'price': 32000.0,
    'stock': 16,
    'category': 'Selai & Spread',
    'images': ['https://via.placeholder.com/300x300?text=Selai+Strawberry'],
    'mainImageIndex': 0,
    'sku': 'SLI-STR-024',
    'hasDiscount': true,
    'discountPrice': 28000.0,
    'discountStartDate': DateTime.now().toIso8601String(),
    'discountEndDate': DateTime.now().add(const Duration(days: 6)).toIso8601String(),
    'minOrder': 1,
    'maxOrder': 6,
    'weightInGrams': 300,
    'length': 8.0,
    'width': 8.0,
    'height': 12.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['selai', 'strawberry', 'homemade', 'alami'],
    'createdAt': DateTime.now().subtract(const Duration(hours: 8)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_025',
    'sellerId': 'seller_002',
    'name': 'Kerupuk Rambak Sapi',
    'description': 'Kerupuk rambak dari kulit sapi pilihan. Gurih dan renyah saat digoreng.',
    'price': 28000.0,
    'stock': 14,
    'category': 'Camilan',
    'images': ['https://via.placeholder.com/300x300?text=Kerupuk+Rambak'],
    'mainImageIndex': 0,
    'sku': 'KRP-RMB-025',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 1,
    'maxOrder': 8,
    'weightInGrams': 200,
    'length': 20.0,
    'width': 15.0,
    'height': 2.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['kerupuk', 'rambak', 'sapi', 'gurih'],
    'createdAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_026',
    'sellerId': 'seller_001',
    'name': 'Mie Ayam Instan Premium',
    'description': 'Mie ayam instan dengan bumbu lengkap dan potongan ayam asli. Praktis dan lezat.',
    'price': 8500.0,
    'stock': 40,
    'category': 'Makanan Instan',
    'images': ['https://via.placeholder.com/300x300?text=Mie+Ayam+Instan'],
    'mainImageIndex': 0,
    'sku': 'MIE-AYM-026',
    'hasDiscount': true,
    'discountPrice': 7500.0,
    'discountStartDate': DateTime.now().subtract(const Duration(hours: 6)).toIso8601String(),
    'discountEndDate': DateTime.now().add(const Duration(days: 4)).toIso8601String(),
    'minOrder': 5,
    'maxOrder': 30,
    'weightInGrams': 85,
    'length': 12.0,
    'width': 8.0,
    'height': 2.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['mie', 'ayam', 'instan', 'praktis'],
    'createdAt': DateTime.now().subtract(const Duration(hours: 4)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_027',
    'sellerId': 'seller_002',
    'name': 'Bumbu Pecel Madiun',
    'description': 'Bumbu pecel khas Madiun dengan rasa pedas manis yang autentik.',
    'price': 15000.0,
    'stock': 35,
    'category': 'Bumbu Masak',
    'images': ['https://via.placeholder.com/300x300?text=Bumbu+Pecel'],
    'mainImageIndex': 0,
    'sku': 'BMB-PCL-027',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 2,
    'maxOrder': 15,
    'weightInGrams': 100,
    'length': 10.0,
    'width': 8.0,
    'height': 3.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['bumbu', 'pecel', 'madiun', 'pedas manis'],
    'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_028',
    'sellerId': 'seller_001',
    'name': 'Telur Ayam Kampung',
    'description': 'Telur ayam kampung segar dari peternakan lokal. Lebih bergizi dari telur biasa.',
    'price': 3500.0,
    'stock': 60,
    'category': 'Telur & Unggas',
    'images': ['https://via.placeholder.com/300x300?text=Telur+Kampung'],
    'mainImageIndex': 0,
    'sku': 'TLR-KMP-028',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 10,
    'maxOrder': 50,
    'weightInGrams': 60,
    'length': 5.0,
    'width': 4.0,
    'height': 6.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['telur', 'ayam', 'kampung', 'segar'],
    'createdAt': DateTime.now().subtract(const Duration(hours: 3)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_029',
    'sellerId': 'seller_002',
    'name': 'Kacang Tanah Goreng',
    'description': 'Kacang tanah goreng dengan bumbu garam yang pas. Camilan sehat dan bergizi.',
    'price': 20000.0,
    'stock': 28,
    'category': 'Camilan',
    'images': ['https://via.placeholder.com/300x300?text=Kacang+Goreng'],
    'mainImageIndex': 0,
    'sku': 'KCG-TNH-029',
    'hasDiscount': true,
    'discountPrice': 18000.0,
    'discountStartDate': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
    'discountEndDate': DateTime.now().add(const Duration(days: 3)).toIso8601String(),
    'minOrder': 2,
    'maxOrder': 12,
    'weightInGrams': 250,
    'length': 15.0,
    'width': 10.0,
    'height': 4.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['kacang', 'tanah', 'goreng', 'bergizi'],
    'createdAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_030',
    'sellerId': 'seller_001',
    'name': 'Saus Tomat Organik',
    'description': 'Saus tomat dari tomat organik tanpa pengawet buatan. Sehat untuk keluarga.',
    'price': 24000.0,
    'stock': 20,
    'category': 'Sambal & Saus',
    'images': ['https://via.placeholder.com/300x300?text=Saus+Tomat'],
    'mainImageIndex': 0,
    'sku': 'SUS-TMT-030',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 1,
    'maxOrder': 8,
    'weightInGrams': 340,
    'length': 8.0,
    'width': 8.0,
    'height': 15.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['saus', 'tomat', 'organik', 'sehat'],
    'createdAt': DateTime.now().subtract(const Duration(hours: 5)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_031',
    'sellerId': 'seller_002',
    'name': 'Ikan Bandeng Presto',
    'description': 'Ikan bandeng presto tanpa duri, siap santap. Bumbu meresap sempurna.',
    'price': 45000.0,
    'stock': 10,
    'category': 'Ikan & Seafood',
    'images': ['https://via.placeholder.com/300x300?text=Bandeng+Presto'],
    'mainImageIndex': 0,
    'sku': 'IKN-BDG-031',
    'hasDiscount': true,
    'discountPrice': 40000.0,
    'discountStartDate': DateTime.now().toIso8601String(),
    'discountEndDate': DateTime.now().add(const Duration(days: 2)).toIso8601String(),
    'minOrder': 1,
    'maxOrder': 4,
    'weightInGrams': 400,
    'length': 20.0,
    'width': 12.0,
    'height': 4.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['ikan', 'bandeng', 'presto', 'tanpa duri'],
    'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_032',
    'sellerId': 'seller_001',
    'name': 'Keripik Pisang Manis',
    'description': 'Keripik pisang dengan rasa manis alami. Camilan sehat untuk segala usia.',
    'price': 12000.0,
    'stock': 45,
    'category': 'Camilan',
    'images': ['https://via.placeholder.com/300x300?text=Keripik+Pisang'],
    'mainImageIndex': 0,
    'sku': 'KRP-PSG-032',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 3,
    'maxOrder': 20,
    'weightInGrams': 100,
    'length': 18.0,
    'width': 12.0,
    'height': 3.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['keripik', 'pisang', 'manis', 'sehat'],
    'createdAt': DateTime.now().subtract(const Duration(hours: 7)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_033',
    'sellerId': 'seller_002',
    'name': 'Bumbu Rawon Jawa Timur',
    'description': 'Bumbu rawon autentik Jawa Timur dengan kluwek asli. Rasa khas dan menggugah selera.',
    'price': 18000.0,
    'stock': 25,
    'category': 'Bumbu Masak',
    'images': ['https://via.placeholder.com/300x300?text=Bumbu+Rawon'],
    'mainImageIndex': 0,
    'sku': 'BMB-RWN-033',
    'hasDiscount': true,
    'discountPrice': 15000.0,
    'discountStartDate': DateTime.now().subtract(const Duration(hours: 8)).toIso8601String(),
    'discountEndDate': DateTime.now().add(const Duration(days: 5)).toIso8601String(),
    'minOrder': 2,
    'maxOrder': 10,
    'weightInGrams': 75,
    'length': 10.0,
    'width': 8.0,
    'height': 2.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['bumbu', 'rawon', 'jawa timur', 'kluwek'],
    'createdAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_034',
    'sellerId': 'seller_001',
    'name': 'Susu Almond Murni',
    'description': 'Susu almond murni tanpa gula tambahan. Kaya protein dan vitamin E.',
    'price': 35000.0,
    'stock': 18,
    'category': 'Minuman',
    'images': ['https://via.placeholder.com/300x300?text=Susu+Almond'],
    'mainImageIndex': 0,
    'sku': 'SSU-ALM-034',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 1,
    'maxOrder': 6,
    'weightInGrams': 500,
    'length': 8.0,
    'width': 8.0,
    'height': 15.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['susu', 'almond', 'murni', 'vitamin E'],
    'createdAt': DateTime.now().subtract(const Duration(hours: 9)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_035',
    'sellerId': 'seller_002',
    'name': 'Emping Melinjo Gurih',
    'description': 'Emping melinjo dengan rasa gurih yang pas. Camilan tradisional yang lezat.',
    'price': 25000.0,
    'stock': 20,
    'category': 'Camilan',
    'images': ['https://via.placeholder.com/300x300?text=Emping+Melinjo'],
    'mainImageIndex': 0,
    'sku': 'EMP-MLJ-035',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 1,
    'maxOrder': 8,
    'weightInGrams': 150,
    'length': 20.0,
    'width': 15.0,
    'height': 2.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['emping', 'melinjo', 'gurih', 'tradisional'],
    'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_036',
    'sellerId': 'seller_001',
    'name': 'Pasta Tomat Homemade',
    'description': 'Pasta tomat buatan rumah dengan tomat segar pilihan. Tanpa pengawet.',
    'price': 28000.0,
    'stock': 15,
    'category': 'Sambal & Saus',
    'images': ['https://via.placeholder.com/300x300?text=Pasta+Tomat'],
    'mainImageIndex': 0,
    'sku': 'PST-TMT-036',
    'hasDiscount': true,
    'discountPrice': 25000.0,
    'discountStartDate': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
    'discountEndDate': DateTime.now().add(const Duration(days: 4)).toIso8601String(),
    'minOrder': 1,
    'maxOrder': 6,
    'weightInGrams': 250,
    'length': 8.0,
    'width': 8.0,
    'height': 10.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['pasta', 'tomat', 'homemade', 'segar'],
    'createdAt': DateTime.now().subtract(const Duration(hours: 6)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_037',
    'sellerId': 'seller_002',
    'name': 'Ikan Teri Nasi Kering',
    'description': 'Ikan teri nasi kering berkualitas premium. Cocok untuk tumisan dan sambal.',
    'price': 42000.0,
    'stock': 12,
    'category': 'Ikan & Seafood',
    'images': ['https://via.placeholder.com/300x300?text=Teri+Nasi'],
    'mainImageIndex': 0,
    'sku': 'IKN-TRI-037',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 1,
    'maxOrder': 5,
    'weightInGrams': 200,
    'length': 15.0,
    'width': 10.0,
    'height': 3.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['ikan', 'teri', 'nasi', 'kering'],
    'createdAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_038',
    'sellerId': 'seller_001',
    'name': 'Kue Kering Nastar',
    'description': 'Kue kering nastar dengan selai nanas asli. Cocok untuk lebaran dan acara spesial.',
    'price': 55000.0,
    'stock': 8,
    'category': 'Roti & Kue',
    'images': ['https://via.placeholder.com/300x300?text=Kue+Nastar'],
    'mainImageIndex': 0,
    'sku': 'KUE-NST-038',
    'hasDiscount': true,
    'discountPrice': 50000.0,
    'discountStartDate': DateTime.now().toIso8601String(),
    'discountEndDate': DateTime.now().add(const Duration(days: 7)).toIso8601String(),
    'minOrder': 1,
    'maxOrder': 3,
    'weightInGrams': 500,
    'length': 20.0,
    'width': 15.0,
    'height': 8.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['kue', 'nastar', 'nanas', 'lebaran'],
    'createdAt': DateTime.now().subtract(const Duration(days: 3)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_039',
    'sellerId': 'seller_002',
    'name': 'Bumbu Soto Betawi',
    'description': 'Bumbu soto Betawi lengkap dengan santan instan. Praktis dan autentik.',
    'price': 16000.0,
    'stock': 30,
    'category': 'Bumbu Masak',
    'images': ['https://via.placeholder.com/300x300?text=Bumbu+Soto'],
    'mainImageIndex': 0,
    'sku': 'BMB-STO-039',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 2,
    'maxOrder': 12,
    'weightInGrams': 80,
    'length': 10.0,
    'width': 8.0,
    'height': 2.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['bumbu', 'soto', 'betawi', 'santan'],
    'createdAt': DateTime.now().subtract(const Duration(hours: 4)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_040',
    'sellerId': 'seller_001',
    'name': 'Minuman Jahe Merah',
    'description': 'Minuman jahe merah instan untuk menghangatkan badan. Baik untuk kesehatan.',
    'price': 22000.0,
    'stock': 25,
    'category': 'Minuman',
    'images': ['https://via.placeholder.com/300x300?text=Jahe+Merah'],
    'mainImageIndex': 0,
    'sku': 'MNM-JHE-040',
    'hasDiscount': true,
    'discountPrice': 19000.0,
    'discountStartDate': DateTime.now().subtract(const Duration(hours: 2)).toIso8601String(),
    'discountEndDate': DateTime.now().add(const Duration(days: 3)).toIso8601String(),
    'minOrder': 2,
    'maxOrder': 10,
    'weightInGrams': 200,
    'length': 12.0,
    'width': 8.0,
    'height': 15.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['minuman', 'jahe', 'merah', 'hangat'],
    'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_041',
    'sellerId': 'seller_002',
    'name': 'Kerupuk Kampung Asli',
    'description': 'Kerupuk kampung dengan resep tradisional. Renyah dan gurih alami.',
    'price': 18000.0,
    'stock': 35,
    'category': 'Camilan',
    'images': ['https://via.placeholder.com/300x300?text=Kerupuk+Kampung'],
    'mainImageIndex': 0,
    'sku': 'KRP-KMP-041',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 2,
    'maxOrder': 15,
    'weightInGrams': 150,
    'length': 20.0,
    'width': 15.0,
    'height': 2.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['kerupuk', 'kampung', 'tradisional', 'renyah'],
    'createdAt': DateTime.now().subtract(const Duration(hours: 5)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_042',
    'sellerId': 'seller_001',
    'name': 'Minyak Zaitun Extra Virgin',
    'description': 'Minyak zaitun extra virgin import berkualitas tinggi. Sehat untuk memasak dan salad.',
    'price': 85000.0,
    'stock': 6,
    'category': 'Minyak & Bumbu',
    'images': ['https://via.placeholder.com/300x300?text=Minyak+Zaitun'],
    'mainImageIndex': 0,
    'sku': 'MYK-ZTN-042',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 1,
    'maxOrder': 3,
    'weightInGrams': 500,
    'length': 8.0,
    'width': 8.0,
    'height': 20.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['minyak', 'zaitun', 'extra virgin', 'import'],
    'createdAt': DateTime.now().subtract(const Duration(days: 4)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_043',
    'sellerId': 'seller_002',
    'name': 'Ikan Pindang Serani',
    'description': 'Ikan pindang serani dengan bumbu rempah khas. Siap santap dan tahan lama.',
    'price': 38000.0,
    'stock': 14,
    'category': 'Ikan & Seafood',
    'images': ['https://via.placeholder.com/300x300?text=Pindang+Serani'],
    'mainImageIndex': 0,
    'sku': 'IKN-PND-043',
    'hasDiscount': true,
    'discountPrice': 34000.0,
    'discountStartDate': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
    'discountEndDate': DateTime.now().add(const Duration(days: 2)).toIso8601String(),
    'minOrder': 1,
    'maxOrder': 6,
    'weightInGrams': 300,
    'length': 18.0,
    'width': 12.0,
    'height': 4.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['ikan', 'pindang', 'serani', 'rempah'],
    'createdAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_044',
    'sellerId': 'seller_001',
    'name': 'Cokelat Bubuk Premium',
    'description': 'Cokelat bubuk premium untuk minuman dan kue. Rasa cokelat yang kaya dan pekat.',
    'price': 45000.0,
    'stock': 22,
    'category': 'Bahan Kue',
    'images': ['https://via.placeholder.com/300x300?text=Cokelat+Bubuk'],
    'mainImageIndex': 0,
    'sku': 'CKL-BUB-044',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 1,
    'maxOrder': 5,
    'weightInGrams': 250,
    'length': 10.0,
    'width': 8.0,
    'height': 12.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['cokelat', 'bubuk', 'premium', 'kue'],
    'createdAt': DateTime.now().subtract(const Duration(hours: 8)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_045',
    'sellerId': 'seller_002',
    'name': 'Sambal Ijo Padang',
    'description': 'Sambal ijo khas Padang dengan cabai hijau pilihan. Pedas segar dan menggugah selera.',
    'price': 20000.0,
    'stock': 18,
    'category': 'Sambal & Saus',
    'images': ['https://via.placeholder.com/300x300?text=Sambal+Ijo'],
    'mainImageIndex': 0,
    'sku': 'SMB-IJO-045',
    'hasDiscount': true,
    'discountPrice': 17000.0,
    'discountStartDate': DateTime.now().toIso8601String(),
    'discountEndDate': DateTime.now().add(const Duration(days: 5)).toIso8601String(),
    'minOrder': 1,
    'maxOrder': 10,
    'weightInGrams': 200,
    'length': 8.0,
    'width': 8.0,
    'height': 8.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['sambal', 'ijo', 'padang', 'pedas'],
    'createdAt': DateTime.now().subtract(const Duration(days: 1)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_046',
    'sellerId': 'seller_001',
    'name': 'Tepung Terigu Protein Tinggi',
    'description': 'Tepung terigu dengan protein tinggi untuk roti dan kue. Hasil maksimal terjamin.',
    'price': 18000.0,
    'stock': 40,
    'category': 'Bahan Kue',
    'images': ['https://via.placeholder.com/300x300?text=Tepung+Terigu'],
    'mainImageIndex': 0,
    'sku': 'TPG-TRG-046',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 2,
    'maxOrder': 15,
    'weightInGrams': 1000,
    'length': 25.0,
    'width': 18.0,
    'height': 5.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['tepung', 'terigu', 'protein tinggi', 'roti'],
    'createdAt': DateTime.now().subtract(const Duration(hours: 3)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_047',
    'sellerId': 'seller_002',
    'name': 'Ikan Tongkol Asap',
    'description': 'Ikan tongkol asap dengan proses pengasapan tradisional. Aroma dan rasa yang khas.',
    'price': 55000.0,
    'stock': 8,
    'category': 'Ikan & Seafood',
    'images': ['https://via.placeholder.com/300x300?text=Tongkol+Asap'],
    'mainImageIndex': 0,
    'sku': 'IKN-TKL-047',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 1,
    'maxOrder': 3,
    'weightInGrams': 400,
    'length': 25.0,
    'width': 12.0,
    'height': 5.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['ikan', 'tongkol', 'asap', 'tradisional'],
    'createdAt': DateTime.now().subtract(const Duration(days: 3)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_048',
    'sellerId': 'seller_001',
    'name': 'Kecap Manis Organik',
    'description': 'Kecap manis dari kedelai organik tanpa MSG. Rasa manis alami dan sehat.',
    'price': 32000.0,
    'stock': 28,
    'category': 'Bumbu Masak',
    'images': ['https://via.placeholder.com/300x300?text=Kecap+Manis'],
    'mainImageIndex': 0,
    'sku': 'KCP-MNS-048',
    'hasDiscount': true,
    'discountPrice': 28000.0,
    'discountStartDate': DateTime.now().subtract(const Duration(hours: 4)).toIso8601String(),
    'discountEndDate': DateTime.now().add(const Duration(days: 6)).toIso8601String(),
    'minOrder': 1,
    'maxOrder': 8,
    'weightInGrams': 600,
    'length': 8.0,
    'width': 8.0,
    'height': 18.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['kecap', 'manis', 'organik', 'tanpa MSG'],
    'createdAt': DateTime.now().subtract(const Duration(days: 2)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_049',
    'sellerId': 'seller_002',
    'name': 'Kerupuk Kulit Sapi',
    'description': 'Kerupuk kulit sapi dengan tekstur renyah dan gurih. Camilan favorit keluarga.',
    'price': 24000.0,
    'stock': 20,
    'category': 'Camilan',
    'images': ['https://via.placeholder.com/300x300?text=Kerupuk+Kulit'],
    'mainImageIndex': 0,
    'sku': 'KRP-KLT-049',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 1,
    'maxOrder': 10,
    'weightInGrams': 150,
    'length': 20.0,
    'width': 15.0,
    'height': 2.0,
    'status': 'active',
    'hasHalalCertification': true,
    'tags': ['kerupuk', 'kulit', 'sapi', 'renyah'],
    'createdAt': DateTime.now().subtract(const Duration(hours: 6)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'id': 'product_050',
    'sellerId': 'seller_001',
    'name': 'Sirup Jeruk Nipis Asli',
    'description': 'Sirup jeruk nipis dari buah asli tanpa pewarna buatan. Segar dan menyehatkan.',
    'price': 26000.0,
    'stock': 0,
    'category': 'Minuman',
    'images': ['https://via.placeholder.com/300x300?text=Sirup+Jeruk+Nipis'],
    'mainImageIndex': 0,
    'sku': 'SRP-JRK-050',
    'hasDiscount': false,
    'discountPrice': null,
    'discountStartDate': null,
    'discountEndDate': null,
    'minOrder': 1,
    'maxOrder': 8,
    'weightInGrams': 600,
    'length': 8.0,
    'width': 8.0,
    'height': 18.0,
    'status': 'draft',
    'hasHalalCertification': true,
    'tags': ['sirup', 'jeruk nipis', 'asli', 'segar'],
    'createdAt': DateTime.now().subtract(const Duration(hours: 1)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
];